rabbitmq:
  host: "localhost"          # RabbitMQ sunucu adresi
  port: 5672                 # RabbitMQ portu
  queue_name: "my_queue"   # RabbitMQ kuyruk ad覺
  durable: true              # Kuyruk kal覺c覺 m覺 olsun
